clear all
global ipums "E:\Dropbox\Research\Ding's Proposal\WorkingFile\empirical_v2"
global tempdata "E:\Dropbox\Research\Ding's Proposal\WorkingFile\empirical_v2\temp_data"
global cw_ipums "E:\Dropbox\Research\Ding's Proposal\WorkingFile\empirical_v2\cw_ipums"
global dofiles "E:\Dropbox\Research\Ding's Proposal\WorkingFile\empirical_v2\dofiles"
global datafiles "E:\Dropbox\Research\Ding's Proposal\WorkingFile\empirical_v2\datafiles"
global results "E:\Dropbox\Research\Ding's Proposal\WorkingFile\empirical_v2\results"
cd "$datafiles"

*************generate routiness level for occsoc using Dorn's occ1990dd and cw_occ2000_occ1990***********
	
	*** the following excel file is generated by copying 2nd and 9th column of occ_occsoc_crosswalk_2000_onward
import excel "$cw_ipums\occ_occsoc2000.xlsx",clear
rename A occ
rename B occsoc
replace occ = 385 in 383
replace occ = . in 382
replace occ = 485 in 473
replace occ = . in 472
replace occ = 610 in 559
replace occ = . in 558
drop if missing(occ)
save cw_occ00_occsoc,replace

merge 1:1 occ using "$cw_ipums\occ2000_occ1990dd"
sort _merge
drop _merge
merge m:1 occ1990dd using "$cw_ipums\occ1990dd_task_alm"
drop if _merge!=3
replace occsoc="111011" if occsoc=="111031"
replace occsoc="119013" if occsoc=="119011" | occsoc=="119012"
replace occsoc="119199" if occsoc=="119061" | occsoc=="119131"
replace occsoc="172XXX" if occsoc=="172161"
replace occsoc="1930XX" if occsoc=="193020"
replace occsoc="1940XX" if occsoc=="194041"
replace occsoc="2310XX" if occsoc=="231011" | occsoc=="231020"
replace occsoc="397010" if occsoc=="396020" | occsoc=="396030"
replace occsoc="439XXX" if occsoc=="439031" | occsoc=="439199"
replace occsoc="472140" if occsoc=="472141" | occsoc=="472142"
replace occsoc="472221" if occsoc=="472XXX"
replace occsoc="47XXXX" if occsoc=="474090" | occsoc=="474071"
replace occsoc="49909X" if occsoc=="499095"
replace occsoc="514030" if occsoc=="514031" | occsoc=="514032" | occsoc=="514033" | occsoc=="514034"
replace occsoc="5140XX" if occsoc=="514060" | | occsoc=="514070"
replace occsoc="514XXX" if substr(occsoc,1,5)=="51419"
replace occsoc="515111" if occsoc=="515022"
drop if occsoc=="515010" | occsoc=="515021"
replace occsoc="516040" if occsoc=="516041" | occsoc=="516042"
replace occsoc="51606X" if occsoc=="516061" | occsoc=="516062"
replace occsoc="519151" if occsoc=="519130"
replace occsoc="5191XX" if occsoc=="519192"
replace occsoc="533099" if occsoc=="5330XX"
replace occsoc="534031" if occsoc=="534021"
replace occsoc="5350XX" if occsoc=="535031" | occsoc=="535011"
replace occsoc="5371XX" if occsoc=="537XXX"
replace occsoc="999920" if occsoc=="559920"
drop occ
collapse (mean) task_abstract task_routine task_manual, by(occsoc)

/*
******replace 0 with minimum number among obs thereby calculate log******
sum task_manual if task_manual!=0
loc min=round(r(min),0.001)
replace task_manual=`min' if task_manual==0	
sum task_abstract if task_abstract!=0
loc min=round(r(min),0.001)
replace task_abstract=`min' if task_abstract==0
*/
******add 1 to every index
g task_abstract_1 = task_abstract + 1
g task_routine_1 = task_routine + 1
g task_manual_1 = task_manual + 1

g rti1=ln(task_routine_1)-ln(task_abstract_1)-ln(task_manual_1)
g rti2=task_routine-task_abstract-task_manual
gsort -rti1
g rti1_rank=_n
gsort -rti2
g rti2_rank=_n
keep occsoc rti1 rti2 rti1_rank rti2_rank
save rti_soc,replace
